/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LicenseId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const License = IDL.Record({
  'id' : IDL.Nat,
  'servicePack' : IDL.Text,
  'createdAt' : IDL.Int,
  'version' : IDL.Text,
  'licenseKey' : IDL.Text,
  'osName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLicense' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [LicenseId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteLicense' : IDL.Func([LicenseId], [], []),
  'getAllLicenses' : IDL.Func([], [IDL.Vec(License)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLicense' : IDL.Func([LicenseId], [License], ['query']),
  'getLicenses' : IDL.Func([], [IDL.Vec(License)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLicense' : IDL.Func(
      [LicenseId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LicenseId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const License = IDL.Record({
    'id' : IDL.Nat,
    'servicePack' : IDL.Text,
    'createdAt' : IDL.Int,
    'version' : IDL.Text,
    'licenseKey' : IDL.Text,
    'osName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLicense' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [LicenseId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteLicense' : IDL.Func([LicenseId], [], []),
    'getAllLicenses' : IDL.Func([], [IDL.Vec(License)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLicense' : IDL.Func([LicenseId], [License], ['query']),
    'getLicenses' : IDL.Func([], [IDL.Vec(License)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLicense' : IDL.Func(
        [LicenseId, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };